use_frameworks!

target 'Vite-keystore_Example' do
  pod 'Vite-keystore', :path => '../'
  pod 'SwiftLint'
  pod 'SnapKit'

  target 'Vite-keystore_ExampleTests' do
    inherit! :search_paths
    
  end
end
