use_frameworks!

target 'Vite-keystore_Example' do
  pod 'Vite-keystore', :path => '../'
  pod 'KeychainSwift'
  pod 'SwiftLint'
  pod 'SnapKit', '~> 4.0.0'
  pod 'Eureka'

#  pod 'secp256k1_ios', git: 'https://github.com/shamatar/secp256k1_ios.git', inhibit_warnings: true


  pod 'SVProgressHUD'



pod 'secp256k1.swift', '~> 0.1.4'
pod 'CryptoSwift', '~> 0.11'
pod 'scrypt', '~> 1.5'



pod 'libEd25519Blake2b'


  target 'Vite-keystore_ExampleTests' do
    inherit! :search_paths
    
  end
end
